"""Domain models for the Agentic QA Automation system.

This module contains Pydantic models for DOM nodes, action intents generated by LLMs,
and execution logs/reports.
"""

from typing import Literal

from pydantic import BaseModel, Field


class ElementNode(BaseModel):
    """Represents a pruned, interactive DOM node extracted from the page.

    Attributes:
        id: A unique sequential ID assigned to this element during pruning (e.g., qa-1).
        tag: The HTML element tag (e.g., button, input, a).
        text: The text content of the element, truncated if excessively long.
        attributes: Key HTML attributes, e.g., name, placeholder, role, type, etc.
        selector: A CSS/XPath selector that uniquely resolves this element.
    """

    id: str = Field(description="Unique ID generated for LLM identification")
    tag: str = Field(description="HTML tag name of the element")
    text: str = Field(default="", description="Visible text or value of the element")
    attributes: dict[str, str] = Field(
        default_factory=dict, description="Key attributes of the element"
    )
    selector: str = Field(description="Unique Playwright selector for this element")


class ActionIntent(BaseModel):
    """Represents the LLM's decided action to perform on the page.

    Attributes:
        reasoning: Step-by-step thinking justifying the action choice.
        action_type: The interaction type.
        element_id: The ID of the target element (if applicable).
        value: Input value for actions like typing or selection (if applicable).
    """

    reasoning: str = Field(
        description="Detailed thought process explaining why this action is chosen"
    )
    action_type: Literal[
        "click", "type", "select", "scroll", "wait", "done", "fail"
    ] = Field(description="Type of action to execute")
    element_id: str | None = Field(
        default=None, description="The 'id' of the ElementNode to interact with"
    )
    value: str | None = Field(
        default=None, description="The value to type or select, if applicable"
    )


class StepReport(BaseModel):
    """Represents the outcome and state of a single step in the execution loop.

    Attributes:
        step_number: 1-based index of this step in the test run.
        screenshot_path: Local path to the screenshot captured at this step.
        dom_snapshot: List of interactive elements identified at this step.
        action: The action intent that was executed at this step.
        success: True if the action executed successfully, False otherwise.
        error_message: Present if success is False.
    """

    step_number: int = Field(description="1-based step counter")
    screenshot_path: str | None = Field(
        default=None, description="Path to the screenshot for this step"
    )
    dom_snapshot: list[ElementNode] = Field(
        description="The pruned DOM snapshot visible at the start of this step"
    )
    action: ActionIntent = Field(description="The action intent executed in this step")
    success: bool = Field(description="Whether the step executed without error")
    error_message: str | None = Field(
        default=None, description="Error details if the step execution failed"
    )


class TestReport(BaseModel):
    """The final report documenting the entire autonomous test run.

    Attributes:
        target_url: The starting URL of the test.
        task_description: The goal prompt provided by the user.
        steps: Chronological list of steps executed.
        status: The final status of the test run.
        error_message: Details about the failure if status is failure or timeout.
        trace_path: Path to the Playwright zip trace file.
    """

    target_url: str = Field(description="Starting URL of the test application")
    task_description: str = Field(description="Soft prompt target description")
    steps: list[StepReport] = Field(default_factory=list, description="All test steps")
    status: Literal["success", "failure", "timeout"] = Field(
        description="Final execution outcome"
    )
    error_message: str | None = Field(
        default=None, description="Error details if execution did not succeed"
    )
    trace_path: str | None = Field(
        default=None, description="Path to the zip trace file"
    )


class TestCase(BaseModel):
    """Represents a preconfigured test case scenario for a project."""

    __test__ = False

    name: str = Field(description="Name of the test case")
    description: str = Field(description="Natural language instruction prompt")
    max_steps: int | None = Field(
        default=None, description="Optional limit override for loop steps"
    )


class ProjectConfig(BaseModel):
    """Represents the settings and preconfigured tests for a project."""

    name: str = Field(description="Unique name of the project")
    target_url: str = Field(description="Base target URL of the application")
    model: str = Field(default="openai/gpt-4o", description="LiteLLM model identifier")
    api_base: str | None = Field(
        default=None, description="Optional local Ollama base URL"
    )
    max_steps: int = Field(default=15, description="Default step limit for runs")
    ignore_https_errors: bool = Field(
        default=False, description="Whether to ignore HTTPS/SSL certificate errors"
    )
    credentials: dict[str, str] = Field(
        default_factory=dict, description="Key-value credentials mapping"
    )
    tests: list[TestCase] = Field(
        default_factory=list, description="List of preconfigured test cases"
    )
